### ISSUE TITLE
Doesn't play nicely with perlbrew

### ISSUE THREAD

**Issue by DrHyde** [dinkypumpkin/homebrew-get_iplayer#2]
If perlbrew is installed then it's likely that the user will be flitting around between versions of perl, changing whichever one is first in $PATH. get_iplayer uses `#!/usr/bin/env perl`, and if that finds a perlbrewed build of perl it's likely to be a perl that doesn't have all of get_iplayer's dependencies installed such as HTTP::Cookies.

The formula build script should probably patch get_iplayer to use whichever is the first perl in the *default* path, (`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`), which is always (I think) /usr/bin/perl.

Or it should depend on the `perl` homebrew formula and patch get_iplayer to use that build of perl.

**Comment by dinkypumpkin** [comment]
I'm going to leave it as-is. I think it's reasonable to expect perlbrew users to install dependencies, though perhaps I'll include a warning in the caveats for next release. Homebrew perl would have the same issue,  plus someone could force-install it into /usr/local/bin and thwart any straining of the default path. The `#!/usr/bin/env perl` was added to make get_iplayer play nice with perlbrew, and I don't see any reason to preclude the few Homebrew + perlbrew + get_iplayer users from doing things their way.
