### ISSUE TITLE
Move to Homebrew/homebrew-core

### ISSUE THREAD

**Issue by MikeMcQuaid** [dinkypumpkin/homebrew-get_iplayer#4]
Would you be interested in this formula being moved to Homebrew/homebrew-core? Thanks!

**Comment by dinkypumpkin** [comment]
Thanks very much for the invitation, but I'll keep this formula where it is for now.

**Comment by MikeMcQuaid** [comment]
Would you object if I created a new formula for this in Homebrew/homebrew-core? Thanks!

**Comment by dinkypumpkin** [comment]
Yes I would, so don't do that.

**Comment by MikeMcQuaid** [comment]
To clarify my thinking: `get_iplayer` is a popular tool and currently there's no pointer towards this repository in e.g. `brew search iplayer`. It would be great to figure out some sort of mutually acceptable solution to both parties as I'd really like to have this packaged in Homebrew/homebrew-core and I can't promise that I or another maintainer/contributor won't submit this in future and it get accepted there. Thanks again!

**Comment by dinkypumpkin** [comment]
I think you may have overestimated its popularity. I reckon that more people have installed it in the past month than in the previous 5 years, thanks to a perfect storm of BBC changes and Get iPlayer Automator being abandoned by its author. But once those people discover that GiA has been resuscitated, they will return to its warm GUI busom and this formula will once again belong to the hardy few willing to brave the command prompt. I'm also not too concerned that anybody would want to submit get_iplayer to homebrew-core. There has been no sign of interest for 5 years, and I suspect that Perl scares away anyone who might consider it. 

However, upon reflection I'm not so strongly attached after all. Feel free to take the get_iplayer formula into homebrew-core if you still want to. I have pushed an update that makes `brew audit` happy. Let me know if I need to do anything else.

**Comment by MikeMcQuaid** [comment]
> I think you may have overestimated its popularity.

Just for your insights: 1,414 installed it with Homebrew in the last 30 days. I'll submit a PR and CC you there. Thanks!

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-core/pull/14368 was merged 🎉
